dist: xenial
sudo: required
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

env:
  - PLATFORM=solo5 MACHINE=x86_64

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libseccomp-dev bats sudo iproute2 wget -y
  - sudo apt-get install --only-upgrade binutils gcc -y
  - git clone https://github.com/nabla-containers/rumprun
  - export CC=gcc-6
  - export CXX=g++-6
  - (cd rumprun && bash travis_wait.sh 60 git submodule update --init)
  - (cd rumprun && ./build-rr.sh -o obj -j16 -qq ${PLATFORM})

script:
  - export CC=gcc-6
  - export CXX=g++-6
  - (. $TRAVIS_BUILD_DIR/rumprun/obj/config && make gorump_stamp)
  - export GOROOT=$TRAVIS_BUILD_DIR/go
  - (. $TRAVIS_BUILD_DIR/rumprun/obj/config && cd test/gc_test && GOROOT=$TRAVIS_BUILD_DIR/go make hello.spt)
  - (. $TRAVIS_BUILD_DIR/rumprun/obj/config && cd test/gc_test && bash verify_gc_spt.sh)
